### ISSUE TITLE
To-do for 1.0.0

### ISSUE THREAD

**Issue by jgd10** [jgd10/pySALESetup#2]
The project pipeline is up and running. The code is complete and has tests, but there is still a lot to do before it can be released as a 1.0.0.

- [ ] Test against the latest version of iSALE
  - [ ] Test all examples
  - [ ] Test new input file creation routines
- [ ] Add new examples demonstrating new features
  - [ ] Extension zones
  - [ ] Input-file generation
  - [ ] Grain size distribution
  - [ ] Grain library
  - [ ] Regolith scripts
  - [ ] Complex geometry scripts
- [ ] Include examples in the docs

Features to add before 1.0.0:

- [ ] Save geometries
- [ ] Bitmap geometry setup support (import geometry as a .bmp)
